In [1]:
import requests as rq
from bs4 import BeautifulSoup

In [14]:
def getinfo(pg):
  url="https://www.imdb.com/search/title/?release_date=2020&sort=num_votes,desc&page="+str(pg)
  req=rq.get(url)
  content=req.content
  soup=BeautifulSoup(content)
  all=[]
  for x in soup.find_all('div',attrs={'class':'lister-item-content'}):
    movie=x.find('h3',attrs={'class':'lister-item-header'})
    movie_name=movie.find('a')
    rating=x.find('div',attrs={'class':'inline-block ratings-imdb-rating'})
    imdb_rating=rating.find('strong')
    metascore=x.find('span',attrs={'class':'metascore favorable'})
    directors_and_stars=x.find_all('p',attrs={'class':''})
    votes=x.find('span',attrs={'name':'nv'})
    time=x.find('p', attrs= {'class':'text-muted'}).find('span',attrs={'class':'runtime'})
    genre=x.find('p', attrs= {'class':'text-muted'}).find('span',attrs={'class':'genre'})
    description=x.find_all('p',attrs={'class':'text-muted'})
    all1=[]
    
    if movie_name is not None:
      all1.append(movie_name.text)
    else:
      all1.append('unknown')
    if imdb_rating is not None:
      all1.append(imdb_rating.text)
    else:
      all1.append('unknown')
    if description[1] is not None:
      all1.append(description[1].text[1:-1])
    else:
      all1.append('unknown')
    
    if genre is not None:
      all1.append(genre.text[1:-1])
    else:
      all1.append('unknown')
    if votes is not None:
      all1.append(votes.text)
    else:
      all1.append('unknown')
    if time is not None:
      all1.append(time.text)
    else:
      all1.append('unknown')
    if metascore is not None:
      all1.append(metascore.text)
    else:
      all1.append('unknown')
    if directors_and_stars[1] is not None:
      n=directors_and_stars[1].text.split("Stars")
      if n[0] is not None:
        all1.append(n[0].replace('\n',''))
      else:
        all1.append('unknown')
      if n[1] is not None:
        all1.append(n[1].replace('\n',''))
      else:
        all1.append('unknown')
    else:
      all1.append('unknown')
      all1.append('unknown')
    all.append(all1)
        
  
  return all

In [16]:
import pandas as pd
results = []
no_pages=20
for i in range(1, no_pages+1):
    results.append(getinfo(i))
flatten = lambda l: [item for sublist in l for item in sublist]
df = pd.DataFrame(flatten(results),columns=['movie name','imdb rating','description','genre','votes','time','metascore','directors','stars'])
df

             movie name  ...                                              stars
0                 Tenet  ...  :John David Washington, Robert Pattinson, Eliz...
1    The Queen's Gambit  ...  :Anya Taylor-Joy, Chloe Pirrie, Bill Camp, Mar...
2                  Soul  ...  :Jamie Foxx, Tina Fey, Graham Norton, Rachel H...
3     Wonder Woman 1984  ...  :Gal Gadot, Chris Pine, Kristen Wiig, Pedro Pa...
4         Birds of Prey  ...  :Margot Robbie, Rosie Perez, Mary Elizabeth Wi...
..                  ...  ...                                                ...
995          Underwater  ...  :Kristen Stewart, Vincent Cassel, Mamoudou Ath...
996        The Outsider  ...  :Ben Mendelsohn, Bill Camp, Jeremy Bobb, Mare ...
997          Tiger King  ...  :John Reinke, Kelci Saffery, Rick Kirkham, Joh...
998        Coolie No. 1  ...  :Varun Dhawan, Sara Ali Khan, Paresh Rawal, Ja...
999           Bloodshot  ...  :Vin Diesel, Eiza González, Sam Heughan, Toby ...

[1000 rows x 9 columns]